apiVersion: v1
kind: Service
metadata:
  name: cdevents-controller
spec:
  type: ClusterIP
  selector:
    app: cdevents-controller
  ports:
    - name: http
      port: 9898
      protocol: TCP
      targetPort: http
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc
