version: '2'

services:
  cdevents-controller_frontend:
    build: ..
    command: ./cdevents-controller --backend-url http://cdevents-controller_backend:9899/status/200 --otel-service-name=cdevents-controller_frontend
    environment:
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel:4317
    ports:
      - "9898:9898"
  cdevents-controller_backend:
    build: ..
    command: ./cdevents-controller --port 9899 --otel-service-name=cdevents-controller_backend
    environment:
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel:4317
    ports:
      - "9899:9899"
  otel:
    command: --config otel-config.yaml
    image: otel/opentelemetry-collector:0.41.0
    ports:
      - "4317:4317"
    volumes:
      - ${PWD}/otel-config.yaml:/otel-config.yaml
  jaeger:
    image: jaegertracing/all-in-one:1.29.0
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
