receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:

exporters:
  jaeger:
    endpoint: http://jaeger-tracing-collector.observability:14250
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging,jaeger]
