{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cdevents-controller.serviceAccountName" . }}
  labels:
    {{- include "cdevents-controller.labels" . | nindent 4 }}
{{- end -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cdevents-controller.serviceAccountName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - secrets
    verbs:
      - get
      - watch
      - list
      - delete
      - update
      - patch
  - apiGroups:
      - "core.k8sgpt.ai"
    resources:
      - results
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cdevents-controller.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cdevents-controller.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cdevents-controller.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cdevents-controller.serviceAccountName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - secrets
    verbs:
      - get
      - watch
      - list
      - delete
      - update
      - patch
  - apiGroups:
      - "core.k8sgpt.ai"
    resources:
      - results
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cdevents-controller.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cdevents-controller.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cdevents-controller.serviceAccountName" . }}
